export declare const ENV: {
    GOOGLE_VISION_API_KEY: string;
    GOOGLE_APPLICATION_CREDENTIALS: string;
    GEMINI_API_KEY: string;
    FIREBASE_PROJECT_ID: string;
    FIREBASE_PRIVATE_KEY: string;
    FIREBASE_CLIENT_EMAIL: string;
    NODE_ENV: string;
    REGION: string;
    PORT: number;
    MAX_REQUESTS_PER_MINUTE: number;
    MAX_CONCURRENT_SEARCHES: number;
    LOG_LEVEL: string;
    ENABLE_DEBUG_LOGGING: boolean;
    ENABLE_SCRAPING: boolean;
    ENABLE_API_SEARCHES: boolean;
    ENABLE_IMAGE_PROCESSING: boolean;
    JWT_SECRET: string;
    CORS_ORIGIN: string;
    FIRESTORE_COLLECTION_PREFIX: string;
    MAX_ANALYSIS_HISTORY: number;
    SEARCH_TIMEOUT_MS: number;
    IMAGE_PROCESSING_TIMEOUT_MS: number;
    MAX_IMAGE_SIZE_MB: number;
};
export declare function validateEnvironment(): void;
export declare function isDevelopment(): boolean;
export declare function isProduction(): boolean;
export declare function getLogLevel(): string;
export declare function shouldEnableDebugLogging(): boolean;
//# sourceMappingURL=env.d.ts.map